logging.level.ru.yandex.practicum=trace
spring.sql.init.mode=always
spring.datasource.url=jdbc:h2:file:./db/filmorate
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.schema=classpath:resources/schema.sql
spring.datasource.data=classpath:resources/data.sql
lombok.jacksonized.jacksonVersion=2